In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

### unit paths

In [2]:
CURRENT_DIR = Path.cwd()

if CURRENT_DIR.name == "notebooks":
    PROJECT_ROOT = CURRENT_DIR.parent
else:
    PROJECT_ROOT = CURRENT_DIR

RAW_EXCEL_DIR = PROJECT_ROOT / "data" / "raw" / "excel"
RAW_IMAGES_DIR = PROJECT_ROOT / "data" / "raw" / "images"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

print("Project root:", PROJECT_ROOT)
print("Excel folder exists:", RAW_EXCEL_DIR.exists())
print("Images folder exists:", RAW_IMAGES_DIR.exists())
print("Processed folder exists:", PROCESSED_DIR.exists())

Project root: d:\FCAI\Year 3\2nd semster\Cognitive\bender-gestalt-project
Excel folder exists: True
Images folder exists: True
Processed folder exists: True

In [3]:
excel_files = list(RAW_EXCEL_DIR.glob("*.xlsx"))
image_files = list(RAW_IMAGES_DIR.glob("*.jpg"))

print("Excel files:", excel_files)
print("Number of images:", len(image_files))

Excel files: [WindowsPath('d:/FCAI/Year 3/2nd semster/Cognitive/bender-gestalt-project/data/raw/excel/bender_classification_basline.xlsx')]
Number of images: 89

In [4]:
excel_path = excel_files[0]

df = pd.read_excel(excel_path)

print("Shape:", df.shape)
df.head()

Shape: (89, 15)

,رقم الحالة,الاسم,النوع,الصف الدراسي,العمر,التسلسل,موضع الرسم,المسافة بين رسمين,الاتصال أو التصادم,استخدام الهامش,تغيير موضع الورقة,التغيرات في الجشطالت,ملاحظات دالة بشكل عام,التصنيفات المرضية,التعليق العام
0,1,ياسين محمود علي حسن,ذكر,الرابع الإبتدائي,9,تسلسل غير منظم,لا,من 0.75 إلى 1.25 سم,لا يوجد تداخل,لا,لا,"صعوبات الإغلاق, التغير في الانحناءات",لا يوجد,سوي,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...
1,2,عمرو احمد محمد فتحي,ذكر,الرابع الإبتدائي,9,تسلسل منظم,لا,من 0.75 إلى 1.25 سم,لا يوجد تداخل,لا,لا,"صعوبات الإغلاق - التغير في الانحناءات, التغير ...",إعادة رسم الأجزاء (خطوط ثقيلة),سوي,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...
2,3,محمد سيد البدري عبد المطلب,ذكر,الرابع الإبتدائي,9,تسلسل غير منظم,لا,من 0.75 إلى 1.25 سم,لا يوجد تداخل,لا,لا,"صعوبات الإغلاق, صعوبات التقاطع, التغير في الان...","اندفاع وسرعة في الرسم, المداومة",سوي,المفحوص بشكل عام سوي ويتمتع بمستوى متوسط من ال...
3,4,عدي هاني سيد محمد,ذكر,الرابع الإبتدائي,10,تسلسل غير منظم,لا,مسافة صغيرة جداً,لا يوجد تداخل,لا,لا,"صعوبات الإغلاق, صعوبات التقاطع, التغير في الان...",المداومة,سوي,المفحوص بشكل عام سوي ويتمتع بقدرة متوسطة على ا...
4,5,عمر حاتم عمر الفاروق,ذكر,الرابع الإبتدائي,11,تسلسل غير منظم,لا,مسافة صغيرة جداً,تصادم أو نزعة إليه,لا,لا,"التغير في الانحناءات, صعوبة رسم الأشكال المتداخلة",لا يوجد,سوي,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...

In [5]:
df.columns = df.columns.str.strip()
df.columns.tolist()

['رقم الحالة',
 'الاسم',
 'النوع',
 'الصف الدراسي',
 'العمر',
 'التسلسل',
 'موضع الرسم',
 'المسافة بين رسمين',
 'الاتصال أو التصادم',
 'استخدام الهامش',
 'تغيير موضع الورقة',
 'التغيرات في الجشطالت',
 'ملاحظات دالة بشكل عام',
 'التصنيفات المرضية',
 'التعليق العام']

In [6]:
df["التصنيفات المرضية"].value_counts()

التصنيفات المرضية
سوي              83
العصاب            3
التخلف العقلي     2
سوي               1
Name: count, dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   رقم الحالة             89 non-null     int64
 1   الاسم                  89 non-null     str
 2   النوع                  89 non-null     str
 3   الصف الدراسي           89 non-null     str
 4   العمر                  89 non-null     int64
 5   التسلسل                89 non-null     str
 6   موضع الرسم             89 non-null     str
 7   المسافة بين رسمين      89 non-null     str
 8   الاتصال أو التصادم     89 non-null     str
 9   استخدام الهامش         89 non-null     str
 10  تغيير موضع الورقة      89 non-null     str
 11  التغيرات في الجشطالت   89 non-null     str
 12  ملاحظات دالة بشكل عام  89 non-null     str
 13  التصنيفات المرضية      89 non-null     str
 14  التعليق العام          89 non-null     str
dtypes: int64(2), str(13)
memory usage: 10.6 KB

In [8]:
df.columns

Index(['رقم الحالة', 'الاسم', 'النوع', 'الصف الدراسي', 'العمر', 'التسلسل',
       'موضع الرسم', 'المسافة بين رسمين', 'الاتصال أو التصادم',
       'استخدام الهامش', 'تغيير موضع الورقة', 'التغيرات في الجشطالت',
       'ملاحظات دالة بشكل عام', 'التصنيفات المرضية', 'التعليق العام'],
      dtype='str')

In [9]:
data = df.copy()

In [10]:
## remove useless featuers and check for unique values for each other featuer
columns_to_drop = ["الاسم", "رقم الحالة"]
data = data.drop(columns=columns_to_drop)
feature_unique_values = {}
for col in data.columns:
    unique_values = data[col].unique()
    feature_unique_values[col] = unique_values
    
    
for col, unique_values in feature_unique_values.items():
    print(f"Feature: {col}")
    print(f"Unique values: {unique_values}")
    print("-" * 40)

Feature: النوع
Unique values: <StringArray>
['ذكر', 'أنثي']
Length: 2, dtype: str
----------------------------------------
Feature: الصف الدراسي
Unique values: <StringArray>
['الرابع الإبتدائي', 'السادس الإبتدائي', 'الأول إعدادى', 'الثالث إعدادى']
Length: 4, dtype: str
----------------------------------------
Feature: العمر
Unique values: [ 9 10 11 12 13 15 14]
----------------------------------------
Feature: التسلسل
Unique values: <StringArray>
['تسلسل غير منظم', 'تسلسل منظم', 'تسلسل مرتبك', 'تسلسل ثابت']
Length: 4, dtype: str
----------------------------------------
Feature: موضع الرسم
Unique values: <StringArray>
['لا']
Length: 1, dtype: str
----------------------------------------
Feature: المسافة بين رسمين
Unique values: <StringArray>
['من 0.75 إلى 1.25 سم', 'مسافة صغيرة جداً']
Length: 2, dtype: str
----------------------------------------
Feature: الاتصال أو التصادم
Unique values: <StringArray>
['لا يوجد تداخل', 'تصادم أو نزعة إليه', 'تداخل الرسوم']
Length: 3, dtype: str
----------------------------------------
Feature: استخدام الهامش
Unique values: <StringArray>
['لا']
Length: 1, dtype: str
----------------------------------------
Feature: تغيير موضع الورقة
Unique values: <StringArray>
['لا', 'نعم']
Length: 2, dtype: str
----------------------------------------
Feature: التغيرات في الجشطالت
Unique values: <StringArray>
[                                                                                                     ' صعوبات الإغلاق, التغير في الانحناءات',
                                                  'صعوبات الإغلاق - التغير في الانحناءات, التغير في حجم الزوايا- صعوبة رسم الأشكال المتداخلة',
                 'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة',
                                   'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, صعوبة رسم الأشكال المتداخلة',
                                                                                          'التغير في الانحناءات, صعوبة رسم الأشكال المتداخلة',
    'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تبسيط الرسم, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة',
                                                          'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, صعوبة رسم الأشكال المتداخلة',
                                 'صعوبات الإغلاق, التغير في الانحناءات, التغير في حجم الزوايا, صعوبة رسم الأشكال المتداخلة, تدوير محور الرسم',
                                       'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات,  تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة',
                                 'صعوبات الإغلاق, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة',
     'صعوبات الإغلاق ,صعوبات تقاطع , التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, تبسيط الرسم, صعوبة رسم الأشكال المتداخلة',
                                                                                           'صعوبات تقاطع , التغير في الانحناءات, تبسيط الرسم',
                                                                                                     'التغير في الانحناءات, تدوير محور الرسم',
                                      'صعوبات الإغلاق, تبسيط الرسم, التغير في الانحناءات, التغير في حجم الزوايا, صعوبة رسم الأشكال المتداخلة',
                                                                   'التغير في الانحناءات, التغير في حجم الزوايا, صعوبة رسم الأشكال المتداخلة',
                                                ' التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة',
                                                                   'التغير في الإنحناءات, التغير في حجم الزوايا, صعوبة رسم الأشكال المتداخلة',
                                 'صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة',
          'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, تبسيط, صعوبة رسم الأشكال المتداخلة',
                                                                              'التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم',
                                                                       'التغير في حجم الزوايا, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة',
                                                                                    'التغير في حجم الزوايا, تدوير محور الرسم, تجزئة الجشطالت',
                                                                                                                      'التغير في حجم الزوايا',
                                                   'صعوبات الإغلاق, التغير في الانحناءات, التغير في حجم الزوايا, صعوبة رسم الأشكال المتداخلة',
                                                                                                                       'التغير في الانحناءات',
                                                                                                'التغير في الانحناءات, التغير في حجم الزوايا',
                                                                                                                             'صعوبات التقاطع',
                                                                                                'صعوبات الإغلاق, صعوبة رسم الأشكال المتداخلة',
                                                                'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا',
                                                                                'صعوبات الإغلاق, التغير في الانحناءات, التغير في حجم الزوايا',
                                                                                                                             'صعوبات الإغلاق',
                                                              'صعوبات الإغلاق, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم',
                                                                                'صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا',
                                     'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, لا يوجد',
                                                                                                       'صعوبات التقاطع, التغير في الانحناءات',
                                                   'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تبسيط الرسم',
                                                                                                    'التغير في حجم الزوايا, تدوير محور الرسم',
                   'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تجزئة الجشطالت, صعوبة رسم الأشكال المتداخلة',
                      'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تبسيط الرسم, صعوبة رسم الأشكال المتداخلة',
      'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تبسيط الرسم, تجزئة الجشطالت, صعوبة رسم الأشكال المتداخلة',
 'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, تجزئة الجشطالت, صعوبة رسم الأشكال المتداخلة',
    'صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, تبسيط الرسم, تجزئة الجشطالت, صعوبة رسم الأشكال المتداخلة',
                                                                'صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تجزئة الجشطالت',
                                                              'صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم',
                                                                                                             'صعوبات التقاطع, تجزئة الجشطالت',
    'صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, تبسيط الرسم, صعوبة رسم الأشكال المتداخلة',
                                                                                                         'التغير في حجم الزوايا, تبسيط الرسم',
                                       'صعوبات الإغلاق, صعوبات التقاطع, التغير في حجم الزوايا, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة']
Length: 48, dtype: str
----------------------------------------
Feature: ملاحظات دالة بشكل عام
Unique values: <StringArray>
[                                                                                                            'لا يوجد',
                                                                                      'إعادة رسم الأجزاء (خطوط ثقيلة)',
                                                                                     'اندفاع وسرعة في الرسم, المداومة',
                                                                                                           'المداومة ',
                                                                        'استخدام أكثر من اتجاه, رسم فواصل بين الأشكال',
 'استخدام أكثر من اتجاه, إعادة رسم الأجزاء (خطوط ثقيلة), اندفاع وسرعة في الرسم, رسم فواصل بين الأشكال, رسم كاريكاتيري',
                                                               'استخدام أكثر من اتجاه, إعادة رسم الأجزاء (خطوط ثقيلة)',
                                                                            'المداومة, إعادة رسم الأجزاء (خطوط ثقيلة)',
                                                               'إعادة رسم الأجزاء (خطوط ثقيلة), رسم فواصل بين الأشكال',
                                                                      'إعادة رسم الأجزاء (خطوط ثقيلة), رسم كاريكاتيري',
                                                               'رسم فواصل بين الأشكال, إعادة رسم الأجزاء (خطوط ثقيلة)',
                                                                                                      'رسم كاريكاتيري',
                                                                                      'مداومة, رسم فواصل بين الأشكال ',
                                                                                               'رسم فواصل بين الأشكال',
                                          'الرسم من أسفل لأعلى, إعادة رسم الأجزاء (خطوط ثقيلة), اندفاع وسرعة في الرسم',
                                                                          'الرسم من أسفل لأعلى, استخدام أكثر من اتجاه',
                                                               'إعادة رسم الأجزاء (خطوط ثقيلة), اندفاع وسرعة في الرسم',
                                                                                               'استخدام أكثر من اتجاه',
                                                            'المداومة, إعادة رسم الأجزاء (خطوط ثقيلة), رسم كاريكاتيري',
                                                                                                            'المداومة',
                                          'الرسم من أسفل لأعلى, استخدام أكثر من اتجاه, إعادة رسم الأجزاء (خطوط ثقيلة)',
                                                                                     'المداومة, اندفاع وسرعة في الرسم',
                                                                               'استخدام أكثر من اتجاه, رسم كاريكاتيري',
                                                                                     'المداومة, رسم فواصل بين الأشكال']
Length: 24, dtype: str
----------------------------------------
Feature: التصنيفات المرضية
Unique values: <StringArray>
['سوي', 'التخلف العقلي', 'سوي ', 'العصاب']
Length: 4, dtype: str
----------------------------------------
Feature: التعليق العام
Unique values: <StringArray>
[                                                                                                                                                                                                                                    'المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر البصري الحركي - ولكن لديه مستوى بسيط من الشعور  بالخوف من تكوين علاقات شخصية مع الأخرين وصعوبة الإحتفاظ بتلك العلاقات، كما أن لديه بعض المشاعر المكبوتة.  ',
                                                                                                                                                                                          'المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر البصري الحركي - ولكن لديه شعور  بالخوف من تكوين علاقات شخصية مع الأخرين وصعوبة الإحتفاظ بتلك العلاقات، ولديه رغبات أو مشاعر أو ذكريات يحاول كبتها، كما أن لديه استجابة مفرطة للمثيرات الإنفعالية.  \n',
                                                                              'المفحوص بشكل عام سوي ويتمتع بمستوى متوسط من القدرة على التأزر البصري الحركي - ولكن لديه مخاوف تضعف من قدرته على المبادأة أو اتخاذ القرار  كما تجعل لديه شعور  بالخوف من تكوين علاقات شخصية مع الأخرين وصعوبة الإحتفاظ بتلك العلاقات- كما أن لديه استجابة مفرطة للمثيرات الإنفعالية و نقص في القدرة على تحمل الاحباطات وضبط الأنا- ويميل إلى تجنب المواجهة. \n \n',
                                                                                                                     'المفحوص بشكل عام سوي ويتمتع بقدرة متوسطة على التأزر البصري الحركي تحتاج لتحسينها - ولكن لديه مخاوف تضعف من قدرته على المبادأة أو اتخاذ القرار  و تجعل لديه شعور  بالخوف من تكوين علاقات شخصية مع الأخرين وصعوبة الإحتفاظ بتلك العلاقات- كما أن لديه استجابة مفرطة للمثيرات الإنفعالية و مشاعر مكبوتة ونقص في ضبط الأنا.\n',
                                                                                                                                                                                                                                                                         'المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر البصري الحركي - ولكن لديه عداوت مكبوتة وضعف في القدرة على التخطيط - كما أن لديه استجابة مفرطة للمثيرات الإنفعالية.  \n',
                                                                                                                                                                                                                 'المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر البصري الحركي ولكنه يحتاج لتحسين قدرته على رسم الأشكال المتداخلة - و لديه نشاط انفعالي داخلى وشعور بعدم الكفاءة أو العزلة - كما أن لديه استجابة مفرطة للمثيرات الإنفعالية.  \n',
                                   'يعانى المفحوص من ضعف التأزر البصري الحركي - وضعف مستوى القدرة على الإدراك- ولديه شعور بالقلق ومخاوف تضعف من قدرته على المبادأة أو اتخاذ القرار وتجعله يشعر بالخوف من تكوين علاقات شخصية مع الأخرين وصعوبة الإحتفاظ بتلك العلاقات - كما أن لديه صعوبة في المواجهة ونشاط انفعالى داخلى ومكبوتات وجدانية ونقص القدرة على تحمل الإحباطات وشعور بعدم الكفاءة أو العزلة ولديه استجابة مفرطة للمثيرات الإنفعالية. ',
                                                                                                                                               'المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر البصري الحركي ولكنه يحتاج لتحسين قدرته على رسم الأشكال المتداخلة - ويعانى من وجود وساوس ومخاوف تضعف من قدرته على المبادأة أو اتخاذ القرار  وتشعره بالخوف من تكوين العلاقات الشخصية-  ولديه كبت للمشاعر  و استجابة مفرطة للمثيرات الإنفعالية.  \n',
                                                                                                                                                                                'المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر البصري الحركي ولكنه يحتاج لتحسين قدرته على رسم الأشكال المتداخلة - و لديه شعور بالقلق وخوف من تكوين علاقات شخصية - ولديه كبت للمشاعر - ونشاط انفعالي داخلى - كما أن لديه استجابة مفرطة للمثيرات الإنفعالية.  \n',
                             'المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر البصري الحركي - ولكنه يحتاج لتحسين قدرته على رسم الأشكال المتداخلة - كما أن لديه مخاوف تضعف من قدرته على المبادأة أو اتخاذ القرار وتجعله يشعر بالخوف من تكوين علاقات شخصية مع الأخرين وصعوبة الإحتفاظ بتلك العلاقات - ولديه صراعات وتوترات ناتجة عن وجود رغبات أو مشاعر أو ذكريات يحاول كبتها كما أن لديه نقص في ضبط الأنا واستجابة مفرطة للمثيرات الإنفعالية.  \n',
                                                                                                           'المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر البصري الحركي - ولكنه يحتاج لتحسين قدرته على رسم الأشكال المتداخلة - كما أن لديه مخاوف تضعف من قدرته على المبادأة أو اتخاذ القرار وتجعله يشعر بالخوف من تكوين علاقات شخصية مع الأخرين وصعوبة الإحتفاظ بتلك العلاقات - كما أن لديه استجابة مفرطة للمثيرات الإنفعالية وبعض الصراعات.  ',
                                                                                                                                                           'المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر البصري الحركي - ولكنه يحتاج لتحسين قدرته على رسم الأشكال المتداخلة - كما أن لديه شعور بسيط بالخوف من تكوين علاقات شخصية مع الأخرين وصعوبة الإحتفاظ بتلك العلاقات - و لديه مشاعر مكبوتة وصراعات واستجابة مفرطة للمثيرات الإنفعالية.  ',
                                                                           'المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر البصري الحركي - ولكنه يحتاج لتحسين قدرته على رسم الأشكال المتداخلة - كما أن لديه مخاوف تضعف من قدرته على المبادأة أو اتخاذ القرار وتجعله يشعر بالخوف من تكوين علاقات شخصية مع الأخرين وصعوبة الإحتفاظ بتلك العلاقات - كما أن لديه مشاعر مكبوتة وصراعات وصعوبة في مواجهة الواقع واستجابة مفرطة للمثيرات الإنفعالية.  ',
                                                                                                                                                                                                                                   'المفحوصة بشكل عام سوية وتتمتع بالقدرة على التأزر البصري الحركي - ولكن لديها  مخاوف تضعف من قدرتها على المبادأة أو اتخاذ القرار - كما أن لديها مستوى بسيط من الكبت لبعض المشاعر و صعوبة في مواجهة الواقع. \n',
                                                                                                                                                                                                                                                                           'المفحوصة بشكل عام سوية وتتمتع بالقدرة على التأزر البصري الحركي ولكنها تحتاج لتحسين قدرتها على رسم الانحناءات - و لديها كبت لبعض المشاعر، ومقاومة لصراعات داخلية. \n',
                                                                                                             'المفحوصة بشكل عام سوية وتتمتع بالقدرة على التأزر البصري الحركي - وتحتاج لتحسين قدرتها على رسم الأشكال المتداخلة - حيث أن لديها مخاوف من تكوين علاقات شخصية مع الأخرين وصعوبة الإحتفاظ بتلك العلاقات - كما أن لديها مشاعر مكبوتة واستجابة مفرطة للمثيرات الإنفعالية، ولديها شعور بعدم الكفاءة أو العزلة وصعوبة في مواجهة الواقع.  ',
                                                  'المفحوصة بشكل عام تعاني من خلل إدراكي وضعف في القدرة على التأزر البصري الحركي - وتحتاج لتحسين قدرتها الإدراكية - كما تعانى من عداوات ومشاعر مكبوتة واضطراب القدرة على التخطيط - كما أن لديها قلق و وساوس ومخاوف تضعف من قدرتها على المبادأة أو اتخاذ القرار وتجعلها تشعر بالخوف من تكوين علاقات شخصية مع الأخرين وصعوبة الإحتفاظ بتلك العلاقات - ولديها استجابة مفرطة للمثيرات الإنفعالية.  ',
                                                                                                                                                                                                                     'المفحوصة بشكل عام سوية وتتمتع بالقدرة على التأزر البصري الحركي ولكنها تحتاج لتحسين قدرتها على رسم الأشكال المتداخلة - كما أن لديها استجابة مفرطة للمثيرات الإنفعالية، ومشاعر مكبوتة ولديها شعور بعدم الكفاءة أو العزلة.  ',
                                                                                  'المفحوصة بشكل عام تعاني من ضعف في القدرة على التأزر البصري الحركي وخاصة في الأشكال المتداخلة- وتحتاج لتحسين قدرتها الإدراكية - كما أن لديها قلق و وساوس ومخاوف تضعف من قدرتها على المبادأة أو اتخاذ القرار وتجعلها تشعر بالخوف من تكوين علاقات شخصية مع الأخرين وصعوبة الإحتفاظ بتلك العلاقات - و لديها مشاعر مكبوتة واستجابة مفرطة للمثيرات الإنفعالية.  \n',

In [11]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   النوع                  89 non-null     str
 1   الصف الدراسي           89 non-null     str
 2   العمر                  89 non-null     int64
 3   التسلسل                89 non-null     str
 4   موضع الرسم             89 non-null     str
 5   المسافة بين رسمين      89 non-null     str
 6   الاتصال أو التصادم     89 non-null     str
 7   استخدام الهامش         89 non-null     str
 8   تغيير موضع الورقة      89 non-null     str
 9   التغيرات في الجشطالت   89 non-null     str
 10  ملاحظات دالة بشكل عام  89 non-null     str
 11  التصنيفات المرضية      89 non-null     str
 12  التعليق العام          89 non-null     str
dtypes: int64(1), str(12)
memory usage: 9.2 KB

In [12]:

data.columns = data.columns.str.strip()

# clean featuer values from outer border like (سوي ) with (سوي)
for col in data.select_dtypes(include="object").columns:
    data[col] = (
        data[col]
        .astype(str)
        .str.strip()
        .str.replace("\n", " ", regex=False)
        .str.replace("  ", " ", regex=False)
    )

data["التصنيفات المرضية"] = data["التصنيفات المرضية"].str.strip()

data["التصنيفات المرضية"].value_counts()

C:\Users\DELL\AppData\Local\Temp\ipykernel_17404\3239992223.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in data.select_dtypes(include="object").columns:

التصنيفات المرضية
سوي              84
العصاب            3
التخلف العقلي     2
Name: count, dtype: int64

### one hot encoding for our featuer

In [13]:
"""
note after seein the value counts of out featuer, there are a huge number of unique frequncy and combinations of possible values 
so using one hot encoding by pd.get_dummies wil not work. we have to make it manually
"""   

## possible values from sended doc:

gestalt_values = [
    "صعوبات الإغلاق",
    "صعوبات التقاطع",
    "التغير في الانحناءات",
    "التغير في حجم الزوايا",
    "تدوير محور الرسم",
    "تبسيط الرسم",
    "تجزئة الجشطالت",
    "الإضافة",
    "صعوبة رسم الأشكال المتداخلة"
]

notes_values = [
    "الرسم من أسفل لأعلى",
    "استخدام أكثر من اتجاه",
    "المداومة",
    "إعادة رسم الأجزاء (خطوط ثقيلة)",
    "اندفاع وسرعة في الرسم",
    "رسم فواصل بين الأشكال",
    "رسم كاريكاتيري"
]

In [14]:

def normalize_text(text):
    text = str(text).strip() ## handle the outer spaces 
    
    ## handle the inner spaces and words mistaks
    replacements = {
        "،": ",",
        "-": ",",
        "صعوبات تقاطع": "صعوبات التقاطع",
        "صعوبات الإغلاق ": "صعوبات الإغلاق",
        "التغير في الإنحناءات": "التغير في الانحناءات",
        "تبسيط,": "تبسيط الرسم,",
        "تبسيط ": "تبسيط الرسم",
        "مداومة": "المداومة",
    }
    
    for old, new in replacements.items():
        text = text.replace(old, new)
    
    return text

In [15]:
## main one hot encoded func, suitable for any column ->  التغيرات في الجشطالت ,ملاحظات دالة بشكل عام
def create_multi_value_features(df, column_name, possible_values, prefix):
    result = pd.DataFrame(index=df.index)
    
    normalized_col = df[column_name].fillna("لا يوجد").apply(normalize_text) ## normalize the column first to avoid mistaks of words
    
    for value in possible_values:
        result[f"{prefix}_{value}"] = normalized_col.apply(
            lambda x: 1 if value in x else 0
        )
    
    return result

In [16]:
gestalt_features = create_multi_value_features(
    data,
    "التغيرات في الجشطالت",
    gestalt_values,
    "gestalt"
)

notes_features = create_multi_value_features(
    data,
    "ملاحظات دالة بشكل عام",
    notes_values,
    "note"
)

print(gestalt_features.shape)
print(notes_features.shape)

gestalt_features.head()

(89, 9)
(89, 7)

,gestalt_صعوبات الإغلاق,gestalt_صعوبات التقاطع,gestalt_التغير في الانحناءات,gestalt_التغير في حجم الزوايا,gestalt_تدوير محور الرسم,gestalt_تبسيط الرسم,gestalt_تجزئة الجشطالت,gestalt_الإضافة,gestalt_صعوبة رسم الأشكال المتداخلة
0,1,0,1,0,0,0,0,0,0
1,1,0,1,1,0,0,0,0,1
2,1,1,1,1,1,0,0,0,1
3,1,1,1,1,0,0,0,0,1
4,0,0,1,0,0,0,0,0,1

In [17]:
df.loc[0:4,["التغيرات في الجشطالت"]]

                                التغيرات في الجشطالت
0               صعوبات الإغلاق, التغير في الانحناءات
1  صعوبات الإغلاق - التغير في الانحناءات, التغير ...
2  صعوبات الإغلاق, صعوبات التقاطع, التغير في الان...
3  صعوبات الإغلاق, صعوبات التقاطع, التغير في الان...
4  التغير في الانحناءات, صعوبة رسم الأشكال المتداخلة

In [18]:
counts_of_gestalt = {}
for col in gestalt_features.columns:
    counts_of_gestalt[col] = gestalt_features[col].unique()
    
for col, unique_values in counts_of_gestalt.items():
    print(f"Feature: {col}")
    print(f"Unique values: {unique_values}")
    print("-" * 40)

Feature: gestalt_صعوبات الإغلاق
Unique values: [1 0]
----------------------------------------
Feature: gestalt_صعوبات التقاطع
Unique values: [0 1]
----------------------------------------
Feature: gestalt_التغير في الانحناءات
Unique values: [1 0]
----------------------------------------
Feature: gestalt_التغير في حجم الزوايا
Unique values: [0 1]
----------------------------------------
Feature: gestalt_تدوير محور الرسم
Unique values: [0 1]
----------------------------------------
Feature: gestalt_تبسيط الرسم
Unique values: [0 1]
----------------------------------------
Feature: gestalt_تجزئة الجشطالت
Unique values: [0 1]
----------------------------------------
Feature: gestalt_الإضافة
Unique values: [0]
----------------------------------------
Feature: gestalt_صعوبة رسم الأشكال المتداخلة
Unique values: [0 1]
----------------------------------------

In [19]:
gestalt_features = gestalt_features.drop(columns=["gestalt_الإضافة"]) 
## remove this column because it has only 0 values, and it is not useful for our model

In [20]:
counts_of_notes = {}
for col in notes_features.columns:
    counts_of_notes[col] = notes_features[col].unique()
    
for col, unique_values in counts_of_notes.items():
    print(f"Feature: {col}")
    print(f"Unique values: {unique_values}")
    print("-" * 40)

Feature: note_الرسم من أسفل لأعلى
Unique values: [0 1]
----------------------------------------
Feature: note_استخدام أكثر من اتجاه
Unique values: [0 1]
----------------------------------------
Feature: note_المداومة
Unique values: [0 1]
----------------------------------------
Feature: note_إعادة رسم الأجزاء (خطوط ثقيلة)
Unique values: [0 1]
----------------------------------------
Feature: note_اندفاع وسرعة في الرسم
Unique values: [0 1]
----------------------------------------
Feature: note_رسم فواصل بين الأشكال
Unique values: [0 1]
----------------------------------------
Feature: note_رسم كاريكاتيري
Unique values: [0 1]
----------------------------------------

In [21]:
single_value_cols = [
    "النوع",
    "الصف الدراسي",
    "العمر",
    "التسلسل",
    "موضع الرسم",
    "المسافة بين رسمين",
    "الاتصال أو التصادم",
    "استخدام الهامش",
    "تغيير موضع الورقة"
]

target_col = "التصنيفات المرضية"

basic_data = data[single_value_cols].copy()
y = data[target_col].copy()

X_basic = pd.get_dummies(basic_data, drop_first=False)

print("Basic features:", X_basic.shape)
print("Target:")
print(y.value_counts())

Basic features: (89, 20)
Target:
التصنيفات المرضية
سوي              84
العصاب            3
التخلف العقلي     2
Name: count, dtype: int64

In [22]:
X_basic.head()

,العمر,النوع_أنثي,النوع_ذكر,الصف الدراسي_الأول إعدادى,الصف الدراسي_الثالث إعدادى,الصف الدراسي_الرابع الإبتدائي,الصف الدراسي_السادس الإبتدائي,التسلسل_تسلسل ثابت,التسلسل_تسلسل غير منظم,التسلسل_تسلسل مرتبك,التسلسل_تسلسل منظم,موضع الرسم_لا,المسافة بين رسمين_مسافة صغيرة جداً,المسافة بين رسمين_من 0.75 إلى 1.25 سم,الاتصال أو التصادم_تداخل الرسوم,الاتصال أو التصادم_تصادم أو نزعة إليه,الاتصال أو التصادم_لا يوجد تداخل,استخدام الهامش_لا,تغيير موضع الورقة_لا,تغيير موضع الورقة_نعم
0,9,False,True,False,False,True,False,False,True,False,False,True,False,True,False,False,True,True,True,False
1,9,False,True,False,False,True,False,False,False,False,True,True,False,True,False,False,True,True,True,False
2,9,False,True,False,False,True,False,False,True,False,False,True,False,True,False,False,True,True,True,False
3,10,False,True,False,False,True,False,False,True,False,False,True,True,False,False,False,True,True,True,False
4,11,False,True,False,False,True,False,False,True,False,False,True,True,False,False,True,False,True,True,False

In [23]:
X_basic = X_basic.astype(int)

In [32]:
X_basic.head(2)

,العمر,النوع_أنثي,النوع_ذكر,الصف الدراسي_الأول إعدادى,الصف الدراسي_الثالث إعدادى,الصف الدراسي_الرابع الإبتدائي,الصف الدراسي_السادس الإبتدائي,التسلسل_تسلسل ثابت,التسلسل_تسلسل غير منظم,التسلسل_تسلسل مرتبك,التسلسل_تسلسل منظم,موضع الرسم_لا,المسافة بين رسمين_مسافة صغيرة جداً,المسافة بين رسمين_من 0.75 إلى 1.25 سم,الاتصال أو التصادم_تداخل الرسوم,الاتصال أو التصادم_تصادم أو نزعة إليه,الاتصال أو التصادم_لا يوجد تداخل,استخدام الهامش_لا,تغيير موضع الورقة_لا,تغيير موضع الورقة_نعم
0,9,0,1,0,0,1,0,0,1,0,0,1,0,1,0,0,1,1,1,0
1,9,0,1,0,0,1,0,0,0,0,1,1,0,1,0,0,1,1,1,0

In [26]:
y.values

<StringArray>
[          'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي', 'التخلف العقلي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
        'العصاب',           'سوي',        'العصاب',           'سوي',
           'سوي',           'سوي',        'العصاب',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
 'التخلف العقلي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي',           'سوي',           'سوي',           'سوي',
           'سوي']
Length: 89, dtype: str

In [27]:
X = pd.concat(
    [
        X_basic,
        gestalt_features,
        notes_features
    ],
    axis=1
)

final_data = X.copy()
final_data["target"] = y.values

print("Final data shape:", final_data.shape)
final_data.head()

Final data shape: (89, 36)

,العمر,النوع_أنثي,النوع_ذكر,الصف الدراسي_الأول إعدادى,الصف الدراسي_الثالث إعدادى,الصف الدراسي_الرابع الإبتدائي,الصف الدراسي_السادس الإبتدائي,التسلسل_تسلسل ثابت,التسلسل_تسلسل غير منظم,التسلسل_تسلسل مرتبك,...,gestalt_تجزئة الجشطالت,gestalt_صعوبة رسم الأشكال المتداخلة,note_الرسم من أسفل لأعلى,note_استخدام أكثر من اتجاه,note_المداومة,note_إعادة رسم الأجزاء (خطوط ثقيلة),note_اندفاع وسرعة في الرسم,note_رسم فواصل بين الأشكال,note_رسم كاريكاتيري,target
0,9,0,1,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,سوي
1,9,0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,0,0,سوي
2,9,0,1,0,0,1,0,0,1,0,...,0,1,0,0,1,0,1,0,0,سوي
3,10,0,1,0,0,1,0,0,1,0,...,0,1,0,0,1,0,0,0,0,سوي
4,11,0,1,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,سوي

In [28]:
output_path = PROCESSED_DIR / "excel_features_clean.csv"

final_data.to_csv(output_path, index=False, encoding="utf-8-sig")

print("Saved to:", output_path)
print("Shape:", final_data.shape)
print(final_data["target"].value_counts())

Saved to: d:\FCAI\Year 3\2nd semster\Cognitive\bender-gestalt-project\data\processed\excel_features_clean.csv
Shape: (89, 36)
target
سوي              84
العصاب            3
التخلف العقلي     2
Name: count, dtype: int64

In [29]:
value = pd.DataFrame(
    {'col1': [True]}
    ).astype(int)

In [30]:
value

   col1
0     1